try {
    console.log('Start of try runs');

    // gak ada error disini
    console.log('End of try runs');
} catch (err) {
    console.log('Catch is ignored, because are no error')
}